using GermanCourseRegistration.EntityModels;

namespace GermanCourseRegistration.Application.ServiceResults;

public record MaterialOrdersResult(IEnumerable<CourseMaterialOrderItem> CourseMaterialOrderItems);
